config/routes.rb
ResposiveWeb::Application.routes.draw do

  root :to => "exercises#index"

  match ':controller(/:action(/:id))(.:format)'
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  attr_accessible :favorite, :name
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
  attr_accessible :name, :value
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  # GET /exercises
  # GET /exercises.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exercises }
    end
  end
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  # GET /measurements
  # GET /measurements.json
  def index
    @measurements = Measurement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @measurements }
    end
  end

  # GET /measurements/1
  # GET /measurements/1.json
  def show
    @measurement = Measurement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @measurement }
    end
  end

  # GET /measurements/new
  # GET /measurements/new.json
  def new
    @measurement = Measurement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @measurement }
    end
  end

  # GET /measurements/1/edit
  def edit
    @measurement = Measurement.find(params[:id])
  end

  # POST /measurements
  # POST /measurements.json
  def create
    @measurement = Measurement.new(params[:measurement])

    respond_to do |format|
      if @measurement.save
        format.html { redirect_to @measurement, notice: 'Measurement was successfully created.' }
        format.json { render json: @measurement, status: :created, location: @measurement }
      else
        format.html { render action: "new" }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /measurements/1
  # PUT /measurements/1.json
  def update
    @measurement = Measurement.find(params[:id])

    respond_to do |format|
      if @measurement.update_attributes(params[:measurement])
        format.html { redirect_to @measurement, notice: 'Measurement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measurements/1
  # DELETE /measurements/1.json
  def destroy
    @measurement = Measurement.find(params[:id])
    @measurement.destroy

    respond_to do |format|
      format.html { redirect_to measurements_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  # GET /workouts
  # GET /workouts.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @workouts }
    end
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @workout }
    end
  end

  # GET /workouts/new
  # GET /workouts/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workout }
    end
  end

  # GET /workouts/1/edit
  def edit
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/index.html.erb
<div class="exercisesPage">
    <div class="tabCont">
      <div class="allExercisesTab">
        All Exercises
      </div>
      <div class="myExercisesTab">
        myExercises
      </div>
      <div class="clear"></div>
    </div>

    <div class="filter">
        <div class="search">
          <input name="exerciseSearch" placeholder="Find exercise" id="exerciseSearch">
        </div>

      <div class="muscleFilter">
        <div class="muscleList">
          <div class="title">Filter by muscles:</div>
          <div class="selectedMuscle" id="allMuscles">All muscles</div>
          <div class="editFilter href">Edit filter</div>
        </div>
        <div class="clear"></div>
      </div>
      <div class="musclesCont">
        <div class="muscleMap backView">
          <div class="rotateMap"></div>
          <div class="frontMap">
            <img src="<%= path_to_image "exercises/body-map-front.png" %>" />
            <div id="neck" class="muscleButton">
               Neck
            </div>
            <div id="chest" class="muscleButton">
              Chest
            </div>
            <div id="frontDelta" class="muscleButton">
              Front delta
            </div>
            <div id="biceps" class="muscleButton">
              Biceps
            </div>
            <div id="forearm" class="muscleButton">
              Forearm
            </div>
            <div id="abs" class="muscleButton">
              Abs
            </div>
            <div id="oblique" class="muscleButton">
              Oblique
            </div>
            <div id="quadriceps" class="muscleButton">
              Quadriceps
            </div>
            <div id="calf" class="muscleButton">
              Calf
            </div>
            <div id="soleus" class="muscleButton">
              Soleus
            </div>
          </div>
          <div class="backMap">
            <img src="<%= path_to_image "exercises/body-map-back.png" %>" />
            <div id="traps" class="muscleButton">
               Traps
            </div>
            <div id="backDelta" class="muscleButton">
              Back delta
            </div>
            <div id="lateralDelta" class="muscleButton">
              Lateral delta
            </div>
            <div id="triceps" class="muscleButton">
              Triceps
            </div>
            <div id="lats" class="muscleButton">
              Lats
            </div>
            <div id="lowerBack" class="muscleButton">
              Lover back
            </div>
            <div id="buttocks" class="muscleButton">
              Buttocks
            </div>
            <div id="outletAndAdductors" class="muscleButton">
              Outlet and adductors
            </div>
            <div id="thigh" class="muscleButton">
              Thigh
            </div>
            <div id="hamstrings" class="muscleButton">
              Hamstrings
            </div>
          </div>
          <div class="doneEditing href">Done editing</div>
        </div>
      </div>
      <!--<div class="sortByHardness">sort</div>-->
      <!--<div class="sortByFavorite"></div>-->
    </div>

    <div class="contentList">
        <% 3.times do  %>
            <div class="exercise">
                <div class="intro">
                  <div class="name">
                    Name of Exercise
                  </div>
                  <div class="rate">
                    rate
                  </div>
                  <div class="complexity">
                    compl.
                  </div>
                  <div class="clear"></div>
                  <div class="mainMuscles">
                    <span>biceps</span>
                    <span>nec</span>
                  </div>
                  <div class="additionalMuscles">
                    <span>triceps</span>
                    <span>abs</span>
                  </div>
                  <div class="clear"></div>
                </div>

                <div class="fullData">
                  <div class="avatar">
                    <!--<img src="<%= path_to_image "exercises/barbell.jpg" %>" />-->
                    <%= image_tag 'exercises/barbell.jpg' %>
                  </div>
                  <div class="description">
                    <div class="title">Description:</div>
                    <div class="data">
                        Basic information about exercise. For what it's good.
                    </div>
                  </div>
                  <div class="clear"></div>
                  <div class="howTo">
                    <div class="title">How to do:</div>
                    <div class="data">
                        Information about how to do it correctly.
                    </div>
                  </div>
                  <div class="mediaList">
                    <% 4.times do |i| %>
                        <div class="mediaCont">
                          <img src="<%= path_to_image "exercises/barbell-push1.jpg" %>" />
                        </div>
                    <% end %>
                    <div class="clear"></div>
                  </div>
                  <div class="mediaList">
                    <% 0.times do %>
                        <div class="mediaCont">
                          photo is here
                          <!--some img-->
                        </div>
                     <% end %>
                  </div>

                  <div class="authorInfo">
                    Created by: <a href="#">Stiven Sigal</a>
                  </div>

                  <div class="addingBlock">
                    <div class="addingCont">
                        <div class="toFavorite">
                          Add to favorite
                        </div>
                    </div>
                    <div class="addingCont">
                        <div class="toWorkoutCont">
                            <div class="toWorkout">
                              <div class="stabilization">
                                Add to default workout on monday
                              </div>
                            </div>
                            <div class="gearIcon"></div>
                        </div>
                    </div>
                    <div class="clear"></div>
                  </div>


                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/exercises/new.html.erb
<h1>New exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @exercise.name %>
</p>

<p>
  <b>Favorite:</b>
  <%= @exercise.favorite %>
</p>


<%= link_to 'Edit', edit_exercise_path(@exercise) %> |
<%= link_to 'Back', exercises_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workout Planer</title>
  <%= stylesheet_link_tag    "reset", :media => "all" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "exercises", :media => "all" %>

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="viewPort">
    <header>
      <div class="stabilization-cont">
          <div id="logo"> Workout planer</div>
          <div class="activeWorkout">W</div>
          <nav>
              <ul id="main-menu">
                  <li class="active">Plan</li>
                  <li>Exercises</li>
                  <li>Profile</li>
                  <li>Log out</li>
              </ul>
          </nav>
      </div>
      <div class="clear"></div>
    </header>

    <div id="content">
        <%= yield %>
    </div>
    </div>
    <!-- footer goes here -->
</body>
</html>

app/views/measurements/_form.html.erb
<%= form_for(@measurement) do |f| %>
  <% if @measurement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@measurement.errors.count, "error") %> prohibited this measurement from being saved:</h2>

      <ul>
      <% @measurement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.number_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/measurements/edit.html.erb
<h1>Editing measurement</h1>

<%= render 'form' %>

<%= link_to 'Show', @measurement %> |
<%= link_to 'Back', measurements_path %>

app/views/measurements/index.html.erb
<h1>Listing measurements</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @measurements.each do |measurement| %>
  <tr>
    <td><%= measurement.name %></td>
    <td><%= measurement.value %></td>
    <td><%= link_to 'Show', measurement %></td>
    <td><%= link_to 'Edit', edit_measurement_path(measurement) %></td>
    <td><%= link_to 'Destroy', measurement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Measurement', new_measurement_path %>

app/views/measurements/new.html.erb
<h1>New measurement</h1>

<%= render 'form' %>

<%= link_to 'Back', measurements_path %>

app/views/measurements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @measurement.name %>
</p>

<p>
  <b>Value:</b>
  <%= @measurement.value %>
</p>


<%= link_to 'Edit', edit_measurement_path(@measurement) %> |
<%= link_to 'Back', measurements_path %>

app/views/workouts/day.html.erb
<div class="day-cont">
     <div class="title">
          Day name
     </div>
     <div class="exercise-cont">
       <div class="exercise">
             <div class="minimized">
                <span class="name">Chin Up</span>
                <span class="remove">x</span>
             </div>
             <div class="maximized">
               <!-- TODO add full exercise with aproaches -->
             </div>
       </div>
     </div>
</div>

app/views/workouts/index.html.erb
<div id="planer-cont">
    <div class="day-cont">
         <div class="title">
              Monday
         </div>
         <div class="exercise-cont">
           <div class="exercise">
                 <div class="minimized">
                    <span class="name">Chin Up</span>
                    <span class="remove">x</span>
                 </div>
                 <div class="maximized">
                   <!-- TODO add full exercise with aproaches -->
                 </div>
           </div>
         </div>
    </div>

  <div class="day-cont today">
      <div class="title">
           Tuesday
      </div>
      <div class="exercise-cont">
        <div class="exercise">
              <div class="minimized">
                 <span class="name">Chin Up</span>
                 <span class="remove">x</span>
              </div>
              <div class="maximized">
                <!-- TODO add full exercise with aproaches -->
              </div>
        </div>
        <div class="exercise">
              <div class="minimized">
                 <span class="name">Chin Up</span>
                 <span class="remove">x</span>
              </div>
              <div class="maximized">
                <!-- TODO add full exercise with aproaches -->
              </div>
        </div>
        <div class="exercise">
              <div class="minimized">
                 <span class="name">Chin Up</span>
                 <span class="remove">x</span>
              </div>
              <div class="maximized">
                <!-- TODO add full exercise with aproaches -->
              </div>
        </div>
        <div class="exercise">
              <div class="minimized">
                 <span class="name">Chin Up</span>
                 <span class="remove">x</span>
              </div>
              <div class="maximized">
                <!-- TODO add full exercise with aproaches -->
              </div>
        </div>
      </div>
 </div>

  <div class="day-cont">
      <div class="title">
           Wednesday
      </div>
      <div class="exercise-cont">
        <div class="exercise">
              <div class="minimized">
                 <span class="name">Chin Up</span>
                 <span class="remove">x</span>
              </div>
              <div class="maximized">
                <!-- TODO add full exercise with aproaches -->
              </div>
        </div>
      </div>
 </div>

  <div class="day-cont">
      <div class="title">
           Thursday
      </div>
      <div class="exercise-cont">
        <div class="exercise">
              <div class="minimized">
                 <span class="name">Chin Up</span>
                 <span class="remove">x</span>
              </div>
              <div class="maximized">
                <!-- TODO add full exercise with aproaches -->
              </div>
        </div>
      </div>
 </div>

  <div class="day-cont">
      <div class="title">
           Friday
      </div>
      <div class="exercise-cont">
        <div class="exercise">
              <div class="minimized">
                 <span class="name">Chin Up</span>
                 <span class="remove">x</span>
              </div>
              <div class="maximized">
                <!-- TODO add full exercise with aproaches -->
              </div>
        </div>
      </div>
 </div>

  <div class="day-cont">
      <div class="title">
           Saturday
      </div>
      <div class="exercise-cont">
        <div class="exercise">
              <div class="minimized">
                 <span class="name">Chin Up</span>
                 <span class="remove">x</span>
              </div>
              <div class="maximized">
                <!-- TODO add full exercise with aproaches -->
              </div>
        </div>
      </div>
 </div>

  <div class="day-cont">
      <div class="title">
           Sunday
      </div>
      <div class="exercise-cont">
        <div class="exercise">
              <div class="minimized">
                 <span class="name">Chin Up</span>
                 <span class="remove">x</span>
              </div>
              <div class="maximized">
                <!-- TODO add full exercise with aproaches -->
              </div>
        </div>
      </div>
 </div>

</div>

<div id="workouts-panel">
  <div class="my-workouts-cont">
       <div class="title">
             My workouts
       </div>
        <div class="workouts-cont">
             <div class="workout">
                 <span class="is-active"></span>
                 <a href="#" ><span class="name">Chest</span></a>
             </div>
             <div class="workout">
                   <span class="is-active"></span>
                   <a href="#" ><span class="name">Legs</span></a>
              </div>
              <div class="workout">
                   <span class="is-active"></span>
                   <a href="#" ><span class="name">Arms</span></a>
               </div>
        </div>
  </div>
  <div class="saved-workouts-cont">
       <div class="title">
             Saved workouts
       </div>
        <div class="workouts-cont">
             <div class="workout">
                 <span class="is-active"></span>
                 <a href="#" ><span class="name">Joe Chest</span></a>
             </div>
             <div class="workout">
                   <span class="is-active"></span>
                   <a href="#" ><span class="name">Legs by David</span></a>
              </div>
              <div class="workout">
                   <span class="is-active"></span>
                   <a href="#" ><span class="name">Arms from Arni</span></a>
               </div>
        </div>
  </div>
</div>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @workout.name %>
</p>


<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', workouts_path %>